config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include("page.urls")),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('post/', include('post.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

page/urls.py
from django.urls import path
from . import views

app_name = "page"

urlpatterns = [
    path("", views.home, name="home"), 
    path("explore/", views.explore, name="explore"), 
]

post/urls.py
from django.urls import path, include
from . import views

app_name = 'post'

urlpatterns = [
    path('create/', views.post_create, name='create'),
    path('delete/<slug:slug>/', views.post_delete, name='delete'),
    path('edit/<slug:slug>/', views.post_edit, name='edit'),
    path('detail/<slug:slug>/', views.post_detail, name='detail'),
    path('detail/<slug:slug>/API', views.PostDetailAPI.as_view(), name='detail_API'),
    path('post-like/', views.post_like, name='post_like'),
    path('post-save/', views.post_save, name='post_save'),
    path('', include('comment.urls')),
]

templates/loader/PostDetailAPI.html
{% load post_tags %}

{% for cm in comments %}
    <div class="comments">
        <div class="comment-profile">
            <a href="{% url 'profile' cm.user.username %}"><img src="{{cm.user.avatar}}" alt=""></a>
        </div>
        <div class="comment-main">
            <div class="comment-text">
                <a class="user" href="{% url 'profile' cm.user.username %}"><strong>{{cm.user.username}}</strong></a>
                <div>{{cm.text}}</div>
            </div>
            <div class="comment-info">
                <div class="comment-date">{{cm.created|customtimesince}}</div>
                <div class="comment-likes">
                    {% if cm.likes|length > 1 %}
                        <span class="like-counts">{{cm.likes|length}}</span> <span class="like-word">Likes</span>
                    {% else %}
                        <span class="like-counts">{{cm.likes|length}}</span> <span class="like-word">Like</span>
                    {% endif %}
                </div>
                <div class="comment-reply">Reply</div>
            </div>
        </div>
        <div class="comment-like" data-commentId="{{cm.id}}" data-commentAction="{% if request.user.id in cm.likes %}dis{% endif %}like">
            {% if request.user.id in cm.likes %}
                <i style="font-size: 20px;" class="fas fa-heart heart-active"></i>
            {% else %}
                <i style="font-size: 20px;" class="far fa-heart"></i>
            {% endif %}
        </div>
    </div><hr />
{% endfor %}

templates/loader/followers.html
<div>
    <ul>
        {% if search_result.count >= 1 %}
            {% for user in search_result %}
                <li style="list-style-type: none">
                    <div style="display: grid; grid-template-columns: 30% 60%;">
                        <a href="{% url 'profile' user.user_from %}">
                            <img style="height: 4em; width: 4em; border-radius: 50%;" src="{{user.user_from.avatar.url}}" alt="">
                        </a>
                        <div style="margin-top: 1em; color: #999; font-weight: 400; text-align: left;">
                            <span style="font-weight: 600;">
                                <style>
                                    a:focus-visible {
                                        outline: none;
                                        border: none;
                                    }
                                </style>
                                <a id="idk" style="text-decoration: none; color: #333; display: inline-block; width: 100%; font-weight: bold;" href="{% url 'profile' user.user_from %}">{{user.user_from}}</a>
                            </span>
                            {% if user.user_from.first_name %}
                                {{user.user_from.first_name}}
                            {% endif %}
                            {% if user.user_from.last_name %}
                                {{user.user_from.last_name}}
                            {% endif %}
                        </div>
                    </div>
                </li><hr style="color: #333; background-color: #333; background: #333;">
            {% endfor %}
        {% else %}
            <div>No users found.</div>
        {% endif %}
    </ul>
</div>

templates/loader/following.html
<div>
    <ul>
        {% if search_result.count >= 1 %}
            {% for user in search_result %}
                <li style="list-style-type: none">
                    <div style="display: grid; grid-template-columns: 30% 60%;">
                        <a href="{% url 'profile' user.user_to %}">
                            <img style="height: 4em; width: 4em; border-radius: 50%;" src="{{user.user_to.avatar.url}}" alt="">
                        </a>
                        <div style="margin-top: 1em; color: #999; font-weight: 400; text-align: left;">
                            <span style="font-weight: 600;">
                                <style>
                                    a:focus-visible {
                                        outline: none;
                                        border: none;
                                    }
                                </style>
                                <a id="idk" style="text-decoration: none; color: #333; display: inline-block; width: 100%; font-weight: bold;" href="{% url 'profile' user.user_to %}">{{user.user_to}}</a>
                            </span>
                            {% if user.user_to.first_name %}
                                {{user.user_to.first_name}}
                            {% endif %}
                            {% if user.user_to.last_name %}
                                {{user.user_to.last_name}}
                            {% endif %}
                        </div>
                    </div>
                </li><hr style="color: #333; background-color: #333; background: #333;">
            {% endfor %}
        {% else %}
            <div>No users found.</div>
        {% endif %}
    </ul>
</div>

templates/loader/home.html
{% for post in posts %}
    <div class="post_in_main">
        <div class="post-owner-details">
            <div class="post-owner-details-img">
                <a href="{% url 'profile' post.user %}">
                    <img src="{{post.user.avatar.url}}" alt="" />
                </a>
            </div>
            <div class="post-owner-details-profile">
                <div class="post-owner-details-profile-name">{{post.user}}</div>
                <div class="post-owner-details-profile-loaction">Isfahan</div>
            </div>
            <div></div>
            <div class="post-owner-details-settings">...</div>
        </div>
        <a href="{{post.get_absolute_url}}" class="post-main">
            <img src="{{post.image.url}}" alt="" />
        </a>
        <div class="post-actions">
            <div class="heart-family">
                <i class="far fa-heart"></i>
                <i class="far fa-comment"></i>
                <i class="far fa-paper-plane"></i>
            </div>
            <div class="bookmark-family">
                <i class="far fa-bookmark"></i>
            </div>
        </div>
        {% if post.likes.all|length > 1 %}
            <div class="post-likes">{{post.likes.all|length}} likes</div>
        {% else %}
            <div class="post-likes">{{post.likes.all|length}} like</div>
        {% endif %}
        <div class="post-caption">
            <a href="#" class="post-caption-username">{{post.user}}</a>
            <span class="post-caption-main" processed="false">{{post.caption}}</span>
            <a href="#" class="more-caption">more</a>
        </div>
        <div class="post-view-comments">
            {% if post.comments.all|length > 0 %}
                <a href="#">View all {{post.comments.all|length}} comments</a>
            {% endif %}
        </div>
        <div class="post-date">{{post.created|timesince}} ago</div>
        <div class="post-add-comment">
            <div class="emoji">
                <a href=""><i class="far fa-smile"></i></a>
            </div>
            <div class="poast-comment-input">
                <input type="text" placeholder="Add a comment..." />
            </div>
            <div class="post-key">
                <button>Post</button>
            </div>
        </div>
    </div>
{% endfor %}

templates/loader/post_create.html
{% load crispy_forms_tags %}

<form action="{% url 'post:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %} {{media_form|crispy}} {{post_form|crispy}}
    <button type="submit" class="swal2-confirm swal2-styled">Post</button>
</form>

templates/loader/post_delete.html
<h1>Are you sure you want to delete this post?</h1>
<form action="{% url 'post:delete' post.slug %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger" style="margin-top: 15px;">Yes</button>
</form>

templates/loader/post_detail.html
{% load post_tags %}

<div class="comments">
    <div class="comment-profile">
        <a href="{% url 'profile' comment.user %}"><img src="{{comment.user.avatar.url}}" alt="" /></a>
    </div>
    <div class="comment-main">
        <div class="comment-text">
            <a class="user" href="{% url 'profile' comment.user %}"><strong>{{comment.user}}</strong></a>
            <div>{{comment.text}}</div>
        </div>
        <div class="comment-info">
            <div class="comment-date">{{comment.created|customtimesince}}</div>
            <div class="comment-likes">
                {% if comment.likes.all|length > 1 %}
                    <span class="like-counts">{{comment.likes.all|length}}</span> <span class="like-word">Likes</span>
                {% else %}
                    <span class="like-counts">{{comment.likes.all|length}}</span> <span class="like-word">Like</span>
                {% endif %}
            </div>
            <div class="comment-reply">Reply</div>
        </div>
    </div>
    <div class="comment-like" data-commentId="{{comment.id}}" data-commentAction="{% if request.user in comment.likes.all %}dis{% endif %}like">
        {% if request.user in comment.likes.all %}
            <i style="font-size: 20px;" class="fas fa-heart heart-active"></i>
        {% else %}
            <i style="font-size: 20px;" class="far fa-heart"></i>
        {% endif %}
    </div>
</div>
<hr />

templates/loader/post_edit.html
{% load crispy_forms_tags %}

<h1 style="margin: 30px;">Edit your post</h1>
<form action="{% url 'post:edit' post.slug %}" method="POST">
    {% csrf_token %} {{form|crispy}}
    <button type="submit" class="btn btn-primary">Edit</button>
</form>

templates/loader/profile.html
{% load post_tags %}

{% for post in posts %}
    <a class="gallery-item" tabindex="0" href="{{ post.get_absolute_url }}">
        {% if post.media.first|extension == 'image' %}
            <img src="{{post.media.first.media.url}}" alt="gallery-post">
            {% if post.media.count > 1 %}
                <span class="eapps-instagram-feed-posts-item-image-icon-carousel eapps-instagram-feed-posts-item-image-icon es-post-type">
                    <svg viewBox="0 0 45.964 45.964">
                        <path
                            d="M32.399,40.565H11.113v1.297c0,2.24,1.838,4.051,4.076,4.051h26.733c2.239,0,4.042-1.811,4.042-4.051V15.13c0-2.237-1.803-4.068-4.042-4.068h-1.415v21.395C40.507,36.904,36.845,40.566,32.399,40.565z"
                        ></path>
                        <path
                            d="M0,4.102l0,28.355c0,2.241,1.814,4.067,4.051,4.067h28.365c2.237,0,4.066-1.826,4.066-4.067l0-28.356c0-2.238-1.828-4.051-4.066-4.051H4.051C1.814,0.05,0,1.862,0,4.102z"
                        ></path>
                    </svg>
                </span>
            {% endif %}  
        {% else %}
            <video src="{{post.media.first.media.url}}#t=1" alt="gallery-post" preload="auto"></video>
            {% if post.media.count == 1 %}
                <span class="eapps-instagram-feed-posts-item-image-icon-video eapps-instagram-feed-posts-item-image-icon es-post-type">
                    <svg viewBox="0 0 24 24">
                        <path
                            d="M23.467,5.762c-0.118-0.045-0.232-0.068-0.342-0.068c-0.246,0-0.451,0.087-0.615,0.26l-3.76,3.217v5.766l3.76,3.578c0.164,0.173,0.369,0.26,0.615,0.26c0.109,0,0.223-0.023,0.342-0.068C23.822,18.552,24,18.284,24,17.901V6.57C24,6.186,23.822,5.917,23.467,5.762z"
                        ></path>
                        <path
                            d="M16.33,4.412c-0.77-0.769-1.696-1.154-2.78-1.154H3.934c-1.084,0-2.01,0.385-2.78,1.154C0.385,5.182,0,6.108,0,7.192v9.616c0,1.084,0.385,2.01,1.154,2.78c0.77,0.77,1.696,1.154,2.78,1.154h9.616c1.084,0,2.01-0.385,2.78-1.154c0.77-0.77,1.154-1.696,1.154-2.78v-3.076v-3.478V7.192C17.484,6.108,17.099,5.182,16.33,4.412z M8.742,17.229c-2.888,0-5.229-2.341-5.229-5.229c0-2.888,2.341-5.229,5.229-5.229S13.971,9.112,13.971,12C13.971,14.888,11.63,17.229,8.742,17.229z"
                        ></path>
                        <circle cx="8.742" cy="12" r="3.5"></circle>
                    </svg>
                </span>
            {% else %}
                <span class="eapps-instagram-feed-posts-item-image-icon-carousel eapps-instagram-feed-posts-item-image-icon es-post-type">
                    <svg viewBox="0 0 45.964 45.964">
                        <path
                            d="M32.399,40.565H11.113v1.297c0,2.24,1.838,4.051,4.076,4.051h26.733c2.239,0,4.042-1.811,4.042-4.051V15.13c0-2.237-1.803-4.068-4.042-4.068h-1.415v21.395C40.507,36.904,36.845,40.566,32.399,40.565z"
                        ></path>
                        <path
                            d="M0,4.102l0,28.355c0,2.241,1.814,4.067,4.051,4.067h28.365c2.237,0,4.066-1.826,4.066-4.067l0-28.356c0-2.238-1.828-4.051-4.066-4.051H4.051C1.814,0.05,0,1.862,0,4.102z"
                        ></path>
                    </svg>
                </span>
            {% endif %}
        {% endif %}
        <div class="gallery-item-info">
            <ul style="margin-bottom: 10px;">
                <li style="color: white; font-size: 20px; padding-right: 10px;"><i class="fas fa-heart" aria-hidden="true"></i> {{post.total_likes|human_format:"symbolic"}}</li>
                <li style="color: white; font-size: 20px;"><i class="fas fa-comment" aria-hidden="true"></i> {{post.comments.all|length|human_format:"symbolic"}}</li>
            </ul>
            {% if post.caption %}
                <ul style="margin-bottom: 0;">
                    <li style="color: white; font-size: 20px; text-align: center;"><i aria-hidden="true">{{post.caption|truncatechars:100}}</i></li>
                </ul>
            {% endif %}
        </div>
    </a>
{% endfor %}

templates/loader/search.html
<div>
    {% if search_result.count >= 1 %}
        <ul>
            {% for user in search_result %}
                <li style="list-style-type: none">
                    <div style="display: grid; grid-template-columns: 30% 60%;">
                        <a href="{% url 'profile' user %}">
                            <img style="height: 4em; width: 4em; border-radius: 50%;" src="{{user.avatar.url}}" alt="">
                        </a>
                        <div style="margin-top: 1em; color: #999; font-weight: 400;">
                            <span style="font-weight: 600;"">
                                <a style="text-decoration: none; color: #333; display: inline-block; width: 100%; font-weight: bold;" href="{% url 'profile' user %}">{{user}}</a>
                            </span>
                            {% if user.first_name %}
                                {{user.first_name}}
                            {% endif %}
                            {% if user.last_name %}
                                {{user.last_name}}
                            {% endif %}
                        </div>
                    </div>
                </li><hr style="color: #333; background-color: #333; background: #333;">
            {% endfor %}
        </ul>
    {% else %}
        <div>No users and tags found.</div>
    {% endif %}
</div>