config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include("page.urls")),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('post/', include('post.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

page/urls.py
from django.urls import path
from . import views

app_name = "page"

urlpatterns = [
    path("", views.home, name="home"), 
    path("explore/", views.explore, name="explore"), 
]

templates/components/footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/footer.css' %}" />

<footer class="footer" role="contentinfo">
    <div class="footer-container">
        <nav class="footer-nav" role="navigation">
            <ul>
                <li><a href="">About Us</a></li>
                <li><a href="">Support</a></li>
                <li><a href="">Blog</a></li>
                <li><a href="">Press</a></li>
                <li><a href="">Api</a></li>
                <li><a href="">Jobs</a></li>
                <li><a href="">Privacy</a></li>
                <li><a href="">Terms</a></li>
                <li><a href="">Directory</a></li>
                <li>
                    <span class="language"
                        >Language
                        <select name="language" class="select" onchange="la(this.value)">
                            <option value="#">English</option>
                            <option value="#">Russian</option>
                        </select>
                    </span>
                </li>
            </ul>
        </nav>
        <span class="footer-logo">&copy; <script>document.write(new Date().getFullYear());</script> Instagram</span>
    </div>
</footer>

<script>
    function la(src) {
        window.location = src;
    }
</script>

templates/components/header.html
{% load static %}
{% load post_tags %}
<link rel="stylesheet" href="{% static 'css/header.css' %}">

<section id="header-header">
    <div class="header">
        <div class="header-container">
            <div class="logo">
                <img src="{% static 'image/instagram_logo.png' %}" alt="" />
            </div>
            <div>
                <form class="search-bar" method="GET">
                    <input id="search-bar" url="{% url 'search' %}" type="search" name="query" placeholder="Search..." required aria-label="Search" />
                </form>
                <div class="search-container display-none"></div>
            </div>
            <div class="icons">
                <a href="{% url 'page:home' %}" class="home">
                    <i class="fas fa-home"></i>
                </a>
                <div class="send">
                    <i class="far fa-paper-plane"></i>
                </div>
                <div class="add">
                    <i class="far fa-plus-square"></i>
                </div>
                <a href="{% url 'page:explore' %}" class="explore">
                    <i class="far fa-compass"></i>
                </a>
                {% if request.user.is_authenticated %}
                    <div class="heart">
                        {% if actions %}
                            <i class="fa-solid fa-heart fa-beat"></i>
                        {% else %}
                            <i class="fa-regular fa-heart"></i>
                        {% endif %}
                    </div>
                    <div class="profile profile-box" is-authenticated="{{request.user.is_authenticated}}">
                        <img class="profile-box" src="{{request.user.avatar.url}}" alt="" />
                    </div>
                {% else %}
                    <a href="{% url 'page:home' %}"><i class="far fa-heart"></i></a>
                    <a href="{% url 'page:home' %}"><div class="profile profile-box" is-authenticated="{{request.user.is_authenticated}}"><img class="profile-box" src="{% static 'image/no_user_avatar.png' %}" /></div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="actions-container">
        {% for action in actions %}
            <div class="action">
                <div class="action-user-image">
                    <a href="{% url 'profile' action.user %}">
                        <img src="{{action.user.avatar.url}}" alt="" />
                    </a>
                </div>
                <div class="action-act">{{action.act}}</div>
                <div class="action-target">
                    {% if action.act == "followed" or action.act == "unfollowed" %}
                        <a href="{% url 'profile' action.target %}">
                            <img src="{{action.target.avatar.url}}" alt="" />
                        </a>
                    {% elif action.act == "liked" or action.act == "disliked" or action.act == "posted" %}
                        <a href="{{action.target.get_absolute_url}}">
                            <img src="{{action.target.image.url}}" alt="" />
                        </a>
                    {% endif %}
                </div>
                <div class="action-date">{{action.created|customtimesince}} ago</div>
            </div>
        {% endfor %}
    </div>
    <div class="profile-modal-container profile-box display-none">
        <a href="{% url 'profile' request.user %}" class="profile-box profile-link profile-item">
            <i class="far fa-user-circle"></i>
            <span>Profile</span>
        </a>
        <a href="" class="profile-box profile-saves profile-item">
            <i class="far fa-bookmark"></i>
            <span>Saved</span>
        </a>
        <a href="" class="profile-box profile-settings profile-item">
            <i class="fas fa-cog"></i>
            <span>Settings</span>
        </a>
        <a href="" class="profile-box profile-switch-accounts profile-item">
            <i class="fas fa-repeat-alt"></i>
            <span>Switch Accounts</span>
        </a>
        <a href="{% url 'logout' %}?next={% url 'page:explore' %}" class="profile-box logoutbox profile-item">
            <span></span>
            <div>Log Out</div>
        </a>
    </div><hr>
</section>
{% include "components/messages.html" %}

<script src="{% static 'js/header/profile_container.js' %}"></script>
<script src="{% static 'js/header/action_container.js' %}"></script>
<script src="{% static 'js/header/search_container.js' %}"></script>

templates/components/messages.html
<script>
    const swalMessage = function (message, timer=2500) {
        Swal.fire({
            position: "center",
            icon: "success",
            title: message,
            showConfirmButton: false,
            timer: timer,
            background: "black"
        });
    };
</script>

{% if messages %}
        {% for message in messages %} 
        
            {% if message.tags == "error" %}
                <div class="alert alert-danger messages" role="alert">{{message}}</div>
            {% elif message.tags == "warning" %}
                <div class="alert alert-warning messages" role="alert">{{message}}</div>
            {% elif message.tags == "info" %}
                <div class="alert alert-info messages" role="alert">{{message}}</div>

            {% elif message.tags == "success" %}
                {% if message.message == "You are logged in successfully." or message.message == "You are logged out successfully." or message.message == "Password reset successfully." %}
                    <script>swalMessage("{{message}}");</script>
                {% elif message.message == "Email sent successfully." %}
                    <script>swalMessage("{{message}}", 15000);</script>
                {% else %}
                    <div class="alert alert-success messages" role="alert">{{message}}</div>
                {% endif %}
            {% endif %}
            
        {% endfor %}
{% endif %}